### ISSUE TITLE
La cartella tap/bin non esiste più nella repository, ma nell' esempio Flume "hello world" è ancora presente

### ISSUE THREAD

**Issue by nickcacci** [tapunict/tap2023#1]
Nell'esempio di flume "hello world" si presuppone che si parta dalla cartella tap/bin ma la cartella non esiste più.
A seguire la riga proveniente dal file [tap2023](https://github.com/tapunict/tap2023)/[doc](https://github.com/tapunict/tap2023/tree/main/doc)/Apache Flume.ipynb
`# cd tap/bin`

**Comment by nicshub** [comment]
Grazie, lo avevo sistemato in locale ma avevo dimenticato il push.
